### ISSUE TITLE
Message Callback

### ISSUE THREAD

**Issue by Jaew00Shin** [alamin-karno/flutter-crisp-chat#10]
**Is your feature request related to a problem? Please describe.**
I'm using crisp sdk for customer center in my service. Thanks a lot.
But there is only openCrispChat method.
We cannot control any chat messages.

For example, Our customer asked us to notify when they get chat message in crisp after terminating the application.
Our customer send us to message, then they terminated the application if our team didn't reply the message immediately.
After some hours, we replied the message, but customers cannot know whether they got the replied message if they reopen the application.

**Describe the solution you'd like**
So, Could you provide callback method when customer sent or received messages.
For example,

`FlutterCrispChat.onReceiveMessage(void Function(CrispChatMessage message));`

It should work well when the application is foreground, background and terminated.

**Comment by alamin-karno** [comment]
Thanks, @Jaew00Shin for your suggestion. I will try to do this on next update.

**Comment by alamin-karno** [comment]
Thanks, @Jaew00Shin for your suggestion. I will try to do this on next update.

**Comment by Jaew00Shin** [comment]
Could you apply one more suggestion?
I think the method I suggest, "onReceivedMessage", should be provided for the message which the customer sent or received respectively.

For example,
for the message which user sent
`FlutterCrispChat.onSentMessage(void Function(CrispChatMessage message));`

for the message which user received
`FlutterCrispChat.onReceivedMessage(void Function(CrispChatMessage message));`

**Comment by alamin-karno** [comment]
As noted by the Crisp team, the socket connection for the Crisp SDK is only active while the `ChatActivity` is running. This means that new messages will not be detected if the `ChatActivity` is stopped, in the background, or if the app is not in the foreground. The Crisp team is aware of this limitation and is discussing potential solutions, but it is not currently a top priority.
