### ISSUE TITLE
App store submit error

### ISSUE THREAD

**Issue by prasad305** [alamin-karno/flutter-crisp-chat#15]
Asset validation failed
Invalid Executable. The executable 'Runner.app/Frameworks/Crisp.framework/Crisp' contains bitcode. (ID: xxxxxxxxxxxxxxxxxxxx)

**Comment by alamin-karno** [comment]
Can you please provide details information ? @prasad305 

Here is an update. Today I have release new version of crisp chat where update the iOS part of the code. Try to use that and then publish. By the way to use crisp chat you have to make sure you have added all necessary permission information in `Info.plist`

```xml
<key>NSCameraUsageDescription</key>
<string>your usage description here</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>your usage description here</string>
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>
```

**Comment by prasad305** [comment]
Hi @alamin-karno 

![image](https://github.com/user-attachments/assets/67e10ee2-aa98-4c7f-a4da-de651d62ab48)

this is the issue after archive and sumbit to the App store. 

my xcode version 16.0 (16A242d)

**Comment by alamin-karno** [comment]
Check this out: https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm

**Comment by alamin-karno** [comment]
**Verify the Plugin Integration:** 
---
Ensure that the **Flutter Crisp Chat** plugin is correctly installed and up to date in your `pubspec.yaml` file. Check for any breaking changes or updates in the plugin’s documentation.

Example:
```yaml
flutter_crisp_chat: ^latest_version
```
Replace `latest_version` with the latest version available on [pub.dev](https://pub.dev/packages/crisp_chat).
