### ISSUE TITLE
[iOS] Reset crisp chat session throw platform exception

### ISSUE THREAD

**Issue by Maurisz02** [alamin-karno/flutter-crisp-chat#20]
On iOS if I call `FlutterCrispChat.resetCrispChatSession()` it throws a platform exception. I also clone the package to see if this bug also appear in there and the same issue happened. However I can see that the issue is related how session identifier is managed because while the crisp chat is open we can get the session identifier but after we close the crisp chat the session identifier is going to be null and this error happen:

This is what I can see from the package example:
Error retrieving session identifier: Exception: No active session identifier found!

This is what I can see at my project:
PlatformException(INVALID_ARGUMENTS, No arguments passed., null, null)

1. Use `FlutterCrispChat.openCrispChat()` to open an existing crisp chat
2. Close the crisp chat by pressing 'x' or swipe the crisp chat down
3. Press a button which call `FlutterCrispChat.resetCrispChatSession()`

The session identifier should have value after we close the crisp chat so that `FlutterCrispChat.resetCrispChatSession()` reset the session correctly

**Comment by alamin-karno** [comment]
Thanks for your detail's explanation @Maurisz02. I'm fixing this issue and updating the latest version of the package.

**Comment by alamin-karno** [comment]
Crisp Chat Version: [2.0.9](https://github.com/alamin-karno/flutter-crisp-chat/releases/tag/crisp_chat_v2.0.9) Fixed this issue. check now !!
