### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by BghinC** [alamin-karno/flutter-crisp-chat#3]
Hey! I encountered an issue after installing the package. It works fine on iOS, but I received an error when attempting to launch my app on Android.

The error message indicated:

> A problem occurred configuring project ':crisp_chat'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

<details>
<summary>Flutter doctor output</summary>

[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1.2 23B92 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

</details>

Is there some additional configuration to do that should be worth mentioning in the docs?

**Comment by alamin-karno** [comment]
This issue is solved in this version of the package

Try this out: [crisp_chat 1.0.0 ](https://pub.dev/packages/crisp_chat)

**Comment by BghinC** [comment]
Problem solved! Thanks for the update

**Comment by alamin-karno** [comment]
You are welcome @BghinC !!
