### ISSUE TITLE
Execution failed for task ':app:mergeExtDexDebug'.

### ISSUE THREAD

**Issue by ankittiwari25** [alamin-karno/flutter-crisp-chat#35]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/chintanpandya/.gradle/caches/transforms-3/5b226395ff502edd42eacb88070ecf65/transformed/jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/chintanpandya/.gradle/caches/transforms-3/61ec23794cdf31f043a3985932a4d5e1/transformed/appcompat-1.7.0-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Error: Gradle task assembleDebug failed with 
exit code 1
![Uploading Screenshot 2024-12-17 at 15.56.18.png…]()

**Comment by ankittiwari25** [comment]
@alamin-karno  The solution worked, but I am facing one issue:
When the chat opens on an Android device and I click on "Compose your message," the keyboard opens, and the UI shifts upwards. I want the UI to remain stable.

**Comment by alamin-karno** [comment]
Hi @ankittiwari25,

Glad to hear the solution worked! Regarding the UI shift issue on Android when the keyboard opens, this behavior is entirely controlled by the Crisp SDK. Unfortunately, I don't have control over this at the moment. However, if I find a way to resolve it in the future, I'll be sure to include it in the next update.

Since the primary issue has been resolved, I'll go ahead and close this ticket. Feel free to reach out if you have any further questions!

Thanks.
