### ISSUE TITLE
Phoning & custom datas capabilities

### ISSUE THREAD

**Issue by chamartt** [alamin-karno/flutter-crisp-chat#5]
Hello,

First, thank you to your amazing work !

We have two requests to ask you:

- Do you plan to introduce phone calling from the admin to a customer ?
- Do you plan to introduce capability to add custom datas to a customer ?

Thank you !

**Comment by chamartt** [comment]
Hello @alamin-karno ,

To follow our previous conversation, there are the others points to check:

- Possibility to send custom events from the SDK to admin interface
- Possibility to let users notified when we write a message to them

We are really excited to implement this solution.
Unfortunatly, our capacity is not enough to help you asap.

If you need more time or ressource, please let us know and we can find a solution to help you.

Thank again for you time @alamin-karno

**Comment by chamartt** [comment]
Hello @alamin-karno ,

Hope you're good.

I saw you closed the ticket because one of the point has been resolved, what about the others ?

Thanks you for your time.

**Comment by alamin-karno** [comment]
Working on it !!!
