### ISSUE TITLE
Can't get tokenID to work

### ISSUE THREAD

**Issue by VChabrette** [alamin-karno/flutter-crisp-chat#7]
Hello @alamin-karno !

Firstly thanks a lot for your work, the integration was easy as pie and worked great !

However, I don't know if I'm doing something wrong, but I face the following case :
- User A is logged in, and starts a chat
- User A logs out, and User B logs in
- User B opens the chat => I can see all the previous chat from User A and Crisp handles User B as a simple update of User A

From my understanding, this kind of behavior should be prevented by defining the _tokenId_ as the user ID (for example), leading to different sessions for each user.

In my case it's exactly what I did but it doesn't seem to work as intended :( 
![image](https://github.com/alamin-karno/flutter-crisp-chat/assets/3647132/925f41b9-ba39-48ce-b28f-e5b046782bab)

Do you have any idea of what might happen ?

Thanks a lot in advance and keep up the good work !

**Comment by alamin-karno** [comment]
Thanks for sharing your issue. I have run the project again and try the scenario you have told. It's working fine for me. For every new token id, it shows me the new user chat and clears the previous chat.

**Comment by VChabrette** [comment]
Hi ! Thanks a lot for having taken the time to test it on you side

May I ask you how you changed the code of the example project to get the tokenId to change ?
I tried it on my side and have the exact same problem, and I can't see what I'm doing wrong :( 

I went for a very basic random tokenId generation and directly modified the config object (as well as generating a new one each time, but it gave the same result), so maybe I'm doing something wrong
![image](https://github.com/alamin-karno/flutter-crisp-chat/assets/3647132/9d1f5d0e-4420-4ca7-8bfa-e1229342fac2)

For the record, I'm testing on iOS on a real device

Thanks again for your help !

**Comment by alamin-karno** [comment]
Thanks for your issue @VChabrette  !! I have tried that on Android its working fine. 

But for iOS I saw that sometimes the chat cleared but sometime not. Don't know what the issue is. So, I have added a new option to reset the chat session. Hope that this will solve the issue. reset chat session feature will be added in next version of the package. Hopefully today I will update the package.

**Comment by VChabrette** [comment]
Hi @alamin-karno ! 

Firstly, sorry for the late response
I was able to test your new version with the reset chat session feature, and it indeed solved the issue for me ! :D
I just call the reset function each time I display the chat, and it works pretty well, correctly displaying the right chat for the right token !

Thanks again a lot for you help ! :D

**Comment by alamin-karno** [comment]
You're welcome!!! Don't forget to show your love to give star on the project @VChabrette .
